name: Build, Push and Deploy Image

on:
  push:
  pull_request:

env:
  PROJECT_NAME: gruenden-prototype
  IMAGE_NAME: digitalservicebund/gruenden-prototype
  INFRA_REPO: gruenden-infra

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for identity challenge with sigstore/fulcio
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: Build and push
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          sbom: true

      - name: Generate cosign vulnerability scan record
        # Third-party action, pin to commit SHA!
        # See [https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # v0.33.1
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: ghcr.io/${{ env.IMAGE_NAME }}
          format: "cosign-vuln"
          output: "${{ env.PROJECT_NAME }}-vulnerabilities.json"

      - name: Upload cosign vulnerability scan record
        uses: actions/upload-artifact@v5
        with:
          name: "${{ env.PROJECT_NAME }}-vulnerabilities.json"
          path: "${{ env.PROJECT_NAME }}-vulnerabilities.json"
          if-no-files-found: error

      - name: Install cosign
        # Third-party action, pin to commit SHA!
        # See [https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions)
        uses: sigstore/cosign-installer@faadad0cce49287aee09b3a48701e75088a2c6ad # v4.0.0
        with:
          cosign-release: "v2.6.0"

      - name: Sign the published Docker image
        run: cosign sign --yes ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Attest the vulnerability scan
        run: cosign attest --yes --replace --predicate ${{ env.PROJECT_NAME }}-vulnerabilities.json --type vuln ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      # - name: Send failure to Slack
      #   uses: digitalservicebund/notify-on-failure-gha@814d0c4b2ad6a3443e89c991f8657b10126510bf # v1.5.0
      #   if: failure()
      #   with:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy-to-production:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: production
    needs: build-push-image
    steps:
      - name: Deploy latest container image
        uses: digitalservicebund/argocd-deploy@auth-token # Use the auth-token branch for STACKIT
        with:
          environment: production
          version: ${{ github.sha }}
          deploying_repo: ${{ github.event.repository.name }}
          infra_repo: ${{ env.INFRA_REPO }}
          github_app_id: ${{ secrets.GITOPS_INTERNAL_APP_ID }}
          github_app_private_key: ${{ secrets.GITOPS_INTERNAL_APP_PRIVATE_KEY }}
          app: ${{ env.PROJECT_NAME }}-production
          argocd_auth_token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          argocd_server: ${{ secrets.ARGOCD_SERVER_STACKIT }}